name: Deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: npm install
        run: npm ci
      - name: npm test
        run: npm run test
      - name: gcloud auth 
        uses: google-github-actions/gcloud-auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Auth docker
        run: gcloud auth configure-docker
      - name: Build Docker Image
        run: docker build -t gcr.io/$GCP_PROJECT_ID/app:${{ github.sha }} .
      - name: Push Docker image
        run: docker push gcr.io/$GCP_PROJECT_ID/app:${{ github.sha }}
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1